# Generated by Django 5.2.1 on 2025-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='whatsapp_status',
            field=models.BooleanField(default=False),
        ),
    ]
