# Generated by Django 5.2.1 on 2025-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_pledges_whatsapp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
