# Generated by Django 5.2.1 on 2025-10-16 11:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_pledges_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='pledges',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Pledge', 'verbose_name_plural': 'Pledges'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(help_text='Content of the message sent', verbose_name='Message Content'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='method',
            field=models.CharField(choices=[('sms', '📱 SMS'), ('whatsapp', '💬 WhatsApp'), ('email', '✉️ Email'), ('voice_call', '📞 Voice Call'), ('in_person', '🤝 In Person')], help_text='How the message was sent', max_length=20, verbose_name='Communication Method'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pledge',
            field=models.ForeignKey(help_text='The pledge this message relates to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.pledges', verbose_name='Related Pledge'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('queued', '🕐 Queued'), ('pending', '⏳ Pending'), ('sent', '📤 Sent'), ('delivered', '📥 Delivered'), ('failed', '❌ Failed'), ('read', '👁️ Read')], default='pending', help_text='Current status of the message', max_length=20, verbose_name='Message Status'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far (TSH)', max_digits=12, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='event_id',
            field=models.CharField(help_text='Unique identifier for the event', max_length=100, verbose_name='Event ID'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='mobile_number',
            field=models.CharField(help_text='Tanzanian mobile number (e.g., +255123456789)', max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Tanzanian number (e.g., +255123456789 or 0123456789)', regex='^\\+?255[67]\\d{8}$|^\\+?0[67]\\d{8}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='name',
            field=models.CharField(help_text='Full name of the person making the pledge', max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='pledge',
            field=models.DecimalField(decimal_places=2, help_text='Total amount pledged (TSH)', max_digits=12, verbose_name='Pledge Amount'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='status',
            field=models.CharField(choices=[('new', '🆕 New'), ('pending', '⏳ Pending'), ('partial', '📊 Partial Payment'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled')], default='new', help_text='Current status of the pledge', max_length=20, verbose_name='Pledge Status'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='whatsapp_status',
            field=models.BooleanField(default=False, help_text='Whether this mobile number supports WhatsApp', verbose_name='Is WhatsApp Number?'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of this transaction (TSH)', max_digits=12, verbose_name='Transaction Amount'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='method',
            field=models.CharField(choices=[('cash', '💰 Cash'), ('mpesa', '📱 M-Pesa'), ('tigopesa', '📲 Tigo Pesa'), ('airtelmoney', '📞 Airtel Money'), ('bank_transfer', '🏦 Bank Transfer'), ('card', '💳 Card Payment'), ('cheque', '📋 Cheque'), ('other', '🔄 Other')], help_text='How the payment was made', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='pledge',
            field=models.ForeignKey(help_text='The pledge this transaction is for', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.pledges', verbose_name='Related Pledge'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(help_text='Unique identifier for this transaction', max_length=100, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['pledge'], name='messages_pledge__d98bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['method'], name='messages_method_0f6d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['status'], name='messages_status_72d01d_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['created_at'], name='messages_created_919c58_idx'),
        ),
        migrations.AddIndex(
            model_name='pledges',
            index=models.Index(fields=['event_id'], name='pledges_event_i_f0ea8b_idx'),
        ),
        migrations.AddIndex(
            model_name='pledges',
            index=models.Index(fields=['status'], name='pledges_status_a27412_idx'),
        ),
        migrations.AddIndex(
            model_name='pledges',
            index=models.Index(fields=['created_at'], name='pledges_created_ef8c46_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['pledge'], name='transaction_pledge__4441fc_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['method'], name='transaction_method_a21823_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
    ]
