# Generated by Django 5.2.1 on 2025-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_messages_options_alter_pledges_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Event this template belongs to', max_length=100, verbose_name='Event ID')),
                ('message', models.TextField(help_text='The message template content', verbose_name='Template Message')),
                ('type', models.CharField(choices=[('reminder', '🔔 Reminder'), ('new_pledge', '🆕 New Pledge'), ('pledge_completed', '✅ Pledge Completed'), ('card', '💳 Card'), ('thanks', '🙏 Thanks')], help_text='Type/category of this message template', max_length=20, verbose_name='Template Type')),
                ('name', models.CharField(help_text='Descriptive name for this template', max_length=100, verbose_name='Template Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently available for use', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'message_templates',
                'ordering': ['event_id', 'type', 'name'],
                'indexes': [models.Index(fields=['event_id'], name='message_tem_event_i_796166_idx'), models.Index(fields=['type'], name='message_tem_type_5b15ae_idx'), models.Index(fields=['is_active'], name='message_tem_is_acti_f419d4_idx')],
                'unique_together': {('event_id', 'type', 'name')},
            },
        ),
    ]
