# Generated by Django 5.2.1 on 2025-10-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_messagetemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('event_id', 'type')},
        ),
    ]
