# Generated by Django 5.2.1 on 2025-10-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_messagetemplate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together=set(),
        ),
    ]
