# Generated by Django 5.2.1 on 2025-10-20 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_messagetemplate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Email address for account verification and notifications', max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(help_text='Tanzanian mobile number (e.g., +255123456789)', max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Tanzanian number (e.g., +255123456789 or 0123456789)', regex='^\\+?255[67]\\d{8}$|^\\+?0[67]\\d{8}$')], verbose_name='Mobile Number')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the email has been verified', verbose_name='Is Verified')),
                ('verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=100, verbose_name='Verification Token')),
                ('verification_sent_at', models.DateTimeField(blank=True, help_text='When the verification email was last sent', null=True, verbose_name='Verification Sent At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event User',
                'verbose_name_plural': 'Event Users',
                'db_table': 'event_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Tanzanian number (e.g., +255123456789 or 0123456789)', regex='^\\+?255[67]\\d{8}$|^\\+?0[67]\\d{8}$')], verbose_name='Mobile Number')),
                ('event_name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('verification_token', models.CharField(max_length=100, unique=True, verbose_name='Verification Token')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this registration request expires', verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Registration Request',
                'verbose_name_plural': 'Registration Requests',
                'db_table': 'registration_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=200, verbose_name='Event Name')),
                ('date', models.DateTimeField(help_text='Date and time of the event', verbose_name='Event Date')),
                ('description', models.TextField(blank=True, help_text='Description of the event', verbose_name='Event Description')),
                ('location', models.CharField(blank=True, help_text='Location where the event will take place', max_length=200, verbose_name='Event Location')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventuser', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
