# Generated by Django 5.2.1 on 2025-10-20 18:34

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0008_eventuser_registrationrequest_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Event User', 'verbose_name_plural': 'Event Users'},
        ),
        migrations.AlterModelManagers(
            name='eventuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='password',
            field=models.CharField(default=1, help_text='Password for the account (will be hashed)', max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='email',
            field=models.EmailField(help_text='Email address for login and notifications', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the email has been verified', verbose_name='Email Verified'),
        ),
    ]
