# Generated by Django 5.2.1 on 2025-10-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventuser_options_alter_eventuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventuser',
            managers=[
            ],
        ),
    ]
