# Generated by Django 5.2.1 on 2025-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, help_text='When the password reset token expires', null=True, verbose_name='Password Reset Expires'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Token for password reset', max_length=100, null=True, verbose_name='Password Reset Token'),
        ),
    ]
